// Auto-generated by `payload generate:importmap`. The file is committed so
// the admin works on a fresh clone without first running the generator.
// Re-run after adding any custom field/component reference in payload.config.ts.
export const importMap = {};
